name: Build and deploy Node.js app to Azure Web App - pred-model

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read # Required for actions/checkout

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          cache: 'npm'
          cache-dependency-path: modelNodeApp/package-lock.json

      - name: Install dependencies, build, and test
        run: |
          npm install
          npm run build --if-present
          npm run test --if-present
        working-directory: modelNodeApp

      - name: Zip artifact for deployment
        run: zip -r release.zip .
        working-directory: modelNodeApp

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: modelNodeApp/release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write # Required for requesting the JWT
      contents: read # Required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      # - name: Unzip artifact for deployment
      #   run: unzip release.zip -d modelNodeApp

      - name: Unzip artifact for deployment
        run: |
          unzip release.zip -d modelNodeApp
          ls -la modelNodeApp  # List files for debugging


      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_42D1544DB3CA4C6BBD1422888DA74CD9 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_5E37AB559DE749D1BFCDF79B88A788F4 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_CD104DF0A2F14A668E4855CA1707D3C9 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          verbose: true  # Enable debug mode
          app-name: 'pred-model'
          slot-name: 'Production'
          package: modelNodeApp
